#!/bin/sh
#
# Copyright (C) 2006 Stefanos Harhalakis
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# $Id$
#
# Description
#	Umount a mount point
#

NAME="umount"
VERSION="1.0.0"
DESC="Umount a mount point"

# Display help
do_help()
{
	cat << _END
Configuration options:
	MOUNTPOINT	The path to umount or the devicename
_END
}

# Check configuration
# return: 0: ok, 1: error
do_check_conf()
{
	[ -z "$MOUNTPOINT" ] && h_error "Missing MOUNTPOINT" && return 2

	return 0
}

# Do backup
do_run()
{
	if umount "$MOUNTPOINT" ; then
		h_msg 6 "Umounted $MOUNTPOINT"
		R=0
	else
		h_error "Failed to umount $MOUNTPOINT"
		R=1
	fi

	return $R
}

