#!/bin/sh
#
# Copyright (C) 2006 Stefanos Harhalakis
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# $Id$
#
# Description
#
#

# The name of the backup script
NAME="mysql"
# The version of the script
VERSION="0.0.1"
# A short description of the script
DESC="MySQL backup"
# A name for the directory where the backups will be located
DIRNAME="$NAME"

# Display help
do_help()
{
	cat << _END
Configuration options:
	MYUSER		The username to use to connect to the database
	MYPASS		The password (optional) (insecure)
	MYSQL		The full path to mysql executable (optional)
	MYSQLDUMP	The full path to mysqldump executable (optional)
	DATABASES	Space seperated list of databases to backup
			or - for all available databases
_END
}

# Check configuration
# return: 0: ok, 1: error
do_check_conf()
{
	[ -z "$MYUSER" ] && echo "Missing MYUSER" && return 1
	[ -z "$DATABASES" ] && echo "Missing DATABASES" && return 1

	return 0
}

# Get the list of all databases
# Store them in DATABASES
# Return:
#	0: OK
#	1: Error
get_databases()
{
	local	P
	local	R

	if [ ! "$MYPASS" = "" ] ;  then
		P="--password=$MYPASS"
	fi

	# Fetch databases ignoring first line
	DATABASES=`$MYSQL -u $MUSER $P --disable-pager --batch -e 'show databases' | \
			( read T ; while read T ; do echo $T ; done )`

	if [ "$?" = 0 ] ; then
		R=0
	else
		R=1
	fi

	return $R
}

# Do backup
do_run()
{
	 if [ "$DATABASES" = "-" ] ; then
	 	if ! get_databases ; then
			return 1
		fi
	fi

	for db in $DATABASES ; do
		# EDO EDO EDO
	done
}

