#!/bin/sh
#
# Copyright (C) 2006 Stefanos Harhalakis
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# $Id$
#
# Description
#
#	Backup a mysql database
#

NAME="mysql"
VERSION="1.0.0"
DESC="Backup mysql databases"

# Display help
do_help()
{
	cat << _END
Configuration options:
	DATABASES	A space separated list of databases to backup.
			Set this to '-' to backup all databases. (required)
	MYUSER		The username to use to connect (required)
	PASSWORD	The password to use to connect (insecure)
	MYSQL		The path to mysql executable
	MYSQLDUMP	The path to mysqldump executable
	DESTDIR		The destination directory (required)
_END
}

# Check configuration
# return: 0: ok, 1: error
do_check_conf()
{
	[ -z "$DATABASES" ] && h_error "Missing DATABASES" && return 1
	[ -z "$MYUSER" ] && h_error "Missing MYUSER" && return 1
	[ -z "$DESTDIR" ] && h_error "Missing DESTDIR" && return 1

	return 0
}

# Do backup
do_run()
{
	# Initialize
	if [ -z "$MYSQL" ] ; then
		MYSQL="mysql";
	fi

	if [ -z "$MYSQLDUMP" ] ; then
		MYSQLDUMP="mysqldump"
	fi

	if [ ! "$PASSWORD" = "" ] ;  then
		P="--password=$PASSWORD"
	fi


	for t in $MYSQL $MYSQLDUMP ; do
		if ! which $t > /dev/null ; then
			h_error "Could not find '$t'"
			return 1
		fi
	done

	if [ "$DATABASES" = "-" ] ; then
		DATABASES=`$MYSQL -u $MYUSER --disable-pager --batch \
				-e 'show databases'`
	fi

	if ! [ "$?" = 0 ] ; then
		return 1
	fi

	h_formdest "$DESTDIR"
	h_ensuredir "$R_DESTDIR"

	FIRST=1
	for db in $DATABASES ; do
		if [ "$FIRST" = "1" ] ; then
			FIRST="0"
		else
			h_msg 6 "Dumping: $db to $R_DESTDIR/$db.gz"
			$MYSQLDUMP -u $MYUSER -a $db | gzip > $R_DESTDIR/$db.gz
		fi
	done
}


