#!/bin/bash
#
# This file is part of vbackup.
#
# vbackup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# vbackup is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vbackup; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# $Id$
#
# Description
#
#

NAME="openldap"
VERSION="$PACKAGE_VERSION"
DESC="Backup OpenLDAP database"
LICENSE="GPLv2"
COPYRIGHT="Copyright (c) 2012 Stefanos Harhalakis"
CONTACT="v13@v13.gr"

# Display help
do_help()
{
	cat << _END
Configuration options:
	DESTDIR		The destination directory (required)
_END
}

# Check configuration
# return: 0: ok, 1: error
do_check_conf()
{
	[ -z "$DESTDIR" ] && h_error "Missing DESTDIR" && return 1

	return 0
}

# Do backup
do_run()
{
	if [ "x$ABORT" = "x1" ] ; then
		return 0
	fi

	DST1="$DESTDIR/database.ldif"
	DST2="$DESTDIR/config.ldif"

	if h_is_true $COMPRESS ; then
		$SLAPCAT -v | gzip > $DST1.gz
		$SLAPCAT -s cn=config -v | gzip > $DST2.gz
	else
		$SLAPCAT -v > $DST1
		$SLAPCAT -s cn=config -v > $DST2
	fi
}

