#!/bin/sh
#
# Copyright (C) 2006 Stefanos Harhalakis
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# $Id$
#
# Description
#
#	Backup a mysql database
#

NAME="pgsql"
VERSION="1.0.0"
DESC="Backup PostgreSQL databases"

# Display help
do_help()
{
	cat << _END
Configuration options:
	DATABASES	A space separated list of databases to backup.
			Set this to '-' to backup all databases. (required)
	PGUSER		The username to use to connect
	PASSWORD	The password to use to connect
	PSQL		The path to psql executable
	PGDUMP		The path to pg_dump executable
	SUUSER		Do an 'su' to this user (example: postgres)
	DESTDIR		The destination directory (required)
	ALL		Dump template[0-9] too (y/n)
_END
}

# Check configuration
# return: 0: ok, 1: error
do_check_conf()
{
	[ -z "$DATABASES" ] && echo "Missing DATABASES" && return 1
#	[ -z "$USER" ] && echo "Missing USER" && return 1
	[ -z "$DESTDIR" ] && echo "Missing DESTDIR" && return 1

	return 0
}

# Do backup
do_run()
{
	# Initialize
	if [ -z "$PSQL" ] ; then
		PSQL="psql";
	fi

	if [ -z "$PGDUMP" ] ; then
		PGDUMP="pg_dump"
	fi

	for t in $PSQL $PGDUMP ; do
		if ! which $t > /dev/null ; then
			echo "Could not find '$t'"
		fi
	done

	if ! [ -z "$PGUSER" ] ; then
		P_USER="-U $PGUSER"
	fi

	if ! [ -z "$PASSWORD" ] ; then
		export PGPASSWORD="$PASSWORD"
	fi

	if [ "$ALL" = "y" ] || [ "$ALL" = "Y" ] ; then
		P_FILT1=""
	else
		P_FILT1="| grep -v 'template[0-9]'"
	fi

	if [ "$DATABASES" = "-" ] ; then
		CMD="$PSQL -F , -A $P_USER -P tuples_only -P pager=off -l | \
			cut -f 1 -d, $P_FILT1"
		if [ -z "$SUUSER" ] ; then
			DATABASES=`$CMD`
#			DATABASES=`$PSQL -F , -A $P_USER\
#					-P tuples_only -P pager=off -l | \
#					cut -f 1 -d, | \
#					grep -v template0`
		else
			DATABASES=`su - $SUUSER -c "$CMD"`
#			DATABASES=`su - $SUUSER -c "$PSQL -F , -A $P_USER\
#					-P tuples_only -P pager=off -l | \
#					cut -f 1 -d, | \
#					grep -v template0"`
		fi
	fi

	h_formdest "$DESTDIR"
	h_ensuredir "$R_DESTDIR"

	FIRST=1
	for db in $DATABASES ; do
		echo "Dumping: $db to $R_DESTDIR/$db.gz"
		CMD="$PGDUMP $P_USER $db"
		if [ -z "$SUUSER" ] ; then
			$CMD
#			$PGDUMP $P_USER $db | gzip > $R_DESTDIR/$db.gz
		else
			su - $SUUSER -c "$CMD" | gzip > $R_DESTDIR/$db.gz
#			su - $SUUSER -c "$PGDUMP $P_USER $db" | \
#				gzip > $R_DESTDIR/$db.gz
		fi
	done
}

