#!/bin/bash
#
# This file is part of vbackup.
#
# vbackup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# vbackup is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vbackup; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# $Id$
#

NAME="pgsql"

PRI="30"

# The w_do_ask function. Adjust as needed
# $1: The question to ask. First question is always "ENABLE". ASK_NEXT sets
#     the next question
#
# Set ASK_NEXT to the next question or "" for finish
# When ASK_NEXT=="", also return 0/1 to indicate that the script is enabled
# (0: enabled, 1: disabled)
w_do_ask()
{
    local R DEF

    R=1
    case "$1" in
	ENABLE)
	    if ( ! fuser 5432/tcp ) && ( ! test -d /etc/postgresql ) ; then
		DEF='n'
	    else
		DEF='y'
	    fi

	    if h_ask_yesno \
"You can backup your PostgreSQL cluster (if you have one). This will perform
a backup of all databases but only for the 'main' cluster. If you have
multiple clusters you'll have to add more tha one configuration files, one
for each cluster. You'll have to do this by hand" \
		"Perform PostgreSQL backup?" \
		$DEF ; then
		ASK_NEXT="pguser"
	    else
		R=1
		ASK_NEXT=""
	    fi
	;;

	pguser)
	    h_ask_str "" \
		"Enter the username of a postgresql administrative user" \
		"postgres"

	    echo "PGUSER=\"$RET\"" >> $CFG
	    ASK_NEXT="suuser"
	;;

	suuser)
	    h_ask_str \
"You can either use a database password or an existing user that can connect
to PostgreSQL as the administrative user without requiring a password. The
later is recommended. Supplying a password is insecure on multiuser systems.
Either provide a username to 'su' to, or a password to use to connect.
Enter - if you want to use a password instead." \
	    "What username to su to?" \
	    "postgres"

	    if [ "x$RET" = "x-" ] ; then
		ASK_NEXT="password"
	    else
		echo "SUUSER='$RET'" >> $CFG
		ASK_NEXT=""
		R=0
	    fi
	;;

	password)
	    h_ask_str "" "Enter the database administrator password" ""
	    echo "PASSWORD='$RET'" >> $CFG
	    ASK_NEXT=""
	    R=0
	;;
    esac

    return $R
}

# The w_get_config function.
# $1: Backup level
#
# Display configuration file in stdout
w_get_config()
{
    cat $CFG
    cat << _KOKO
DATABASES="-"
DESTDIR="pgsql/%D1%"
_KOKO
}

# vim: set ts=8 sts=4 sw=4 noet formatoptions=r ai nocindent:

