#!/bin/bash
#
# This file is part of vbackup.
#
# vbackup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# vbackup is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vbackup; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# $Id$
#

NAME="mysql"

PRI="30"

# The w_do_ask function. Adjust as needed
# $1: The question to ask. First question is always "ENABLE". ASK_NEXT sets
#     the next question
#
# Set ASK_NEXT to the next question or "" for finish
# When ASK_NEXT=="", also return 0/1 to indicate that the script is enabled
# (0: enabled, 1: disabled)
w_do_ask()
{
    local R DEF

    R=1
    case "$1" in
	ENABLE)
	    if ! test -d /etc/mysql ; then
		DEF='n'
	    else
		DEF='y'
	    fi

	    if h_ask_yesno \
"You can backup your MySQL database (if you have one). This will backup all 
databases." \
		"Perform MySQL backup?" \
		$DEF ; then
		ASK_NEXT="password"
	    else
		ASK_NEXT=""
		R=1
	    fi
	;;

	password)
	    h_ask_str \
"You must enter the password of the root user. You should know that this is
insecure in case of a multiuser system. It is advised to create a .my.cnf
file and enter the password in there. Leave this field empty if you're going
to do this" \
		"Enter the password for the root user" \
		""

	    echo "PASSWORD=\"$RET\"" >> $CFG
	    ASK_NEXT=""
	    R=0
	;;
    esac

    return $R
}

# The w_get_config function.
# $1: Backup level
#
# Display configuration file in stdout
w_get_config()
{
    cat $CFG
    cat << _KOKO
MYUSER="root"
DATABASES="-"
DESTDIR="mysql/"
_KOKO
}

# vim: set ts=8 sts=4 sw=4 noet formatoptions=r ai nocindent:

