#!/bin/bash
#
# This file is part of vbackup.
#
# vbackup is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# vbackup is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vbackup  If not, see <http://www.gnu.org/licenses/>.
#
# $Id$
#

# The name of the backup script
NAME="mbr"

# The priority to be used for the configuration file
PRI="20"

# The variable name in the config file that will hold the backup level
# name.
# - If the method supports multi-level backups (e.g. tar) then this should
#   be set to the variable that needs to hold the leve name (e.g. LEVEL).
#   This will be auto-added to the config file.
# - If the method doesn't support multi-level backups then leave it empty
MULTI=""

# The w_do_ask function. Adjust as needed
# $1: The question to ask. First question is always "ENABLE". ASK_NEXT sets
#     the next question
#
# Set ASK_NEXT to the next question or "" for finish
# When ASK_NEXT=="", also return 0/1 to indicate that the script is enabled
# (0: enabled, 1: disabled)
w_do_ask()
{
    local R

    R=1
    case "$1" in
	ENABLE)
	    if h_ask_yesno \
"It is possible to backup Master Boot Records from local disks,
LVM information, MD information and some other related information.
This can be of great help whenever something bad happens." \
		"Backup Master Boot Records and other related information?" \
		y ; then
		R=0
		echo "VAR=VALUE" > $CFG
	    fi
	    ASK_NEXT=""
	;;
    esac

    return $R
}

# The w_get_config function.
# $1: Backup level
#
# Display configuration file in stdout
w_get_config()
{
    cat $CFG
    cat << _KOKO
DISKS=""
DESTDIR="mbr/"
DESTFILE="mbrs.%D1%"
_KOKO
}

# vim: set ts=8 sts=4 sw=4 noet formatoptions=r ai nocindent:

